### ISSUE TITLE
Upgrade QEMU to 2.5

### ISSUE THREAD

**Issue by wimpers** [openvstorage/qemu#1]
Upgrade QEMU to 2.6

**Comment by saelbrec** [comment]
I checked with partner(Jan DL) and apparently qemu 2.5 which is by default supported in Ubuntu 16.04 that we are targeting is also fine for now.

**Comment by despiegk** [comment]
cool, easier

On Tue, Jun 21, 2016 at 10:29 PM, Stefaan Aelbrecht <
notifications@github.com> wrote:

> I checked with partner(Jan DL) and apparently qemu 2.5 which is by default
> supported in Ubuntu 16.04 that we are targeting is also fine for now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/openvstorage/qemu/issues/1#issuecomment-227561905,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFvi1FZocDB3hhq--8DMsGG0NBcDQ_IVks5qOEnGgaJpZM4I4T0y
> .

## 

---

Kristof De Spiegeleer
+971525609014 (my telegram account registered on this nr, best way to reach
me)
+201206927877
+32 475405474
skype: despiegk

**Comment by wimpers** [comment]
We will upgrade to 2.5 instead of 2.6

**Comment by cnanakos** [comment]
Just pushed a new branch for 2.5 (v2.5-gig) for Ubuntu 16.04.

https://github.com/openvstorage/qemu/tree/v2.5-gig
